name: "test-build"

on: [workflow_dispatch]

jobs:
  test-tauri:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm webkit2gtk-4.1 gtk3 libappindicator-gtk3 librsvg patchelf

      # If tagName and releaseId are omitted tauri-action will only build the app and won't try to upload any assets.
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dsc-build
          path: |
            src-tauri/target/**/release/bundle/**
            src-tauri/target/**/release/*.exe
            src-tauri/target/**/release/*.AppImage
            src-tauri/target/**/release/*.deb
            src-tauri/target/**/release/*.rpm
            src-tauri/target/**/release/*.app
            src-tauri/target/**/release/*.dmg
          if-no-files-found: warn
